"""initial schema

Revision ID: 99b58e1fb222
Revises: 
Create Date: 2026-06-05 11:19:04.500841
"""
from alembic import op
import sqlalchemy as sa


revision = '99b58e1fb222'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('latest_filing_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filer_cik'), 'filer', ['cik'], unique=True)
    op.create_index(op.f('ix_filer_name'), 'filer', ['name'], unique=False)
    op.create_table('security',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('cusip', sa.String(length=9), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_cusip'), 'security', ['cusip'], unique=False)
    op.create_index(op.f('ix_security_key'), 'security', ['key'], unique=True)
    op.create_index(op.f('ix_security_name'), 'security', ['name'], unique=False)
    op.create_index(op.f('ix_security_ticker'), 'security', ['ticker'], unique=False)
    op.create_table('filing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accession_no', sa.String(length=25), nullable=False),
    sa.Column('filer_id', sa.Integer(), nullable=False),
    sa.Column('form_type', sa.String(length=20), nullable=False),
    sa.Column('filed_at', sa.Date(), nullable=False),
    sa.Column('period_of_report', sa.Date(), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filer_id'], ['filer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_no', name='uq_filing_accession')
    )
    op.create_index(op.f('ix_filing_accession_no'), 'filing', ['accession_no'], unique=True)
    op.create_index(op.f('ix_filing_filed_at'), 'filing', ['filed_at'], unique=False)
    op.create_index(op.f('ix_filing_filer_id'), 'filing', ['filer_id'], unique=False)
    op.create_index(op.f('ix_filing_form_type'), 'filing', ['form_type'], unique=False)
    op.create_index(op.f('ix_filing_period_of_report'), 'filing', ['period_of_report'], unique=False)
    op.create_table('holding_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filer_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('prev_period', sa.Date(), nullable=True),
    sa.Column('action', sa.String(length=8), nullable=False),
    sa.Column('shares_delta', sa.BigInteger(), nullable=False),
    sa.Column('value_delta', sa.BigInteger(), nullable=False),
    sa.Column('pct_change', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['filer_id'], ['filer.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_change_filer_period', 'holding_change', ['filer_id', 'period'], unique=False)
    op.create_index(op.f('ix_holding_change_action'), 'holding_change', ['action'], unique=False)
    op.create_index(op.f('ix_holding_change_filer_id'), 'holding_change', ['filer_id'], unique=False)
    op.create_index(op.f('ix_holding_change_period'), 'holding_change', ['period'], unique=False)
    op.create_index(op.f('ix_holding_change_security_id'), 'holding_change', ['security_id'], unique=False)
    op.create_table('fund_holding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('pct_of_net_assets', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['filing_id'], ['filing.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fund_holding_filing_id'), 'fund_holding', ['filing_id'], unique=False)
    op.create_index(op.f('ix_fund_holding_security_id'), 'fund_holding', ['security_id'], unique=False)
    op.create_table('holding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.Column('shares', sa.BigInteger(), nullable=False),
    sa.Column('sh_prn_type', sa.String(length=4), nullable=False),
    sa.Column('put_call', sa.String(length=4), nullable=True),
    sa.Column('investment_discretion', sa.String(length=16), nullable=True),
    sa.Column('voting_sole', sa.BigInteger(), nullable=False),
    sa.Column('voting_shared', sa.BigInteger(), nullable=False),
    sa.Column('voting_none', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filing.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holding_filing_id'), 'holding', ['filing_id'], unique=False)
    op.create_index('ix_holding_filing_security', 'holding', ['filing_id', 'security_id'], unique=False)
    op.create_index(op.f('ix_holding_security_id'), 'holding', ['security_id'], unique=False)
    op.create_table('insider_txn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('insider_name', sa.String(length=255), nullable=False),
    sa.Column('insider_title', sa.String(length=255), nullable=True),
    sa.Column('is_director', sa.Boolean(), nullable=False),
    sa.Column('is_officer', sa.Boolean(), nullable=False),
    sa.Column('is_ten_pct_owner', sa.Boolean(), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=True),
    sa.Column('txn_code', sa.String(length=4), nullable=True),
    sa.Column('is_derivative', sa.Boolean(), nullable=False),
    sa.Column('security_title', sa.String(length=255), nullable=True),
    sa.Column('shares', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('price', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('acquired_disposed', sa.String(length=1), nullable=True),
    sa.Column('shares_owned_after', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['filing_id'], ['filing.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insider_txn_filing_id'), 'insider_txn', ['filing_id'], unique=False)
    op.create_index(op.f('ix_insider_txn_insider_name'), 'insider_txn', ['insider_name'], unique=False)
    op.create_index(op.f('ix_insider_txn_security_id'), 'insider_txn', ['security_id'], unique=False)
    op.create_index(op.f('ix_insider_txn_txn_date'), 'insider_txn', ['txn_date'], unique=False)
    op.create_table('ownership_stake',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('percent_of_class', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('shares', sa.BigInteger(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('is_activist', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filing.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ownership_stake_filing_id'), 'ownership_stake', ['filing_id'], unique=False)
    op.create_index(op.f('ix_ownership_stake_security_id'), 'ownership_stake', ['security_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ownership_stake_security_id'), table_name='ownership_stake')
    op.drop_index(op.f('ix_ownership_stake_filing_id'), table_name='ownership_stake')
    op.drop_table('ownership_stake')
    op.drop_index(op.f('ix_insider_txn_txn_date'), table_name='insider_txn')
    op.drop_index(op.f('ix_insider_txn_security_id'), table_name='insider_txn')
    op.drop_index(op.f('ix_insider_txn_insider_name'), table_name='insider_txn')
    op.drop_index(op.f('ix_insider_txn_filing_id'), table_name='insider_txn')
    op.drop_table('insider_txn')
    op.drop_index(op.f('ix_holding_security_id'), table_name='holding')
    op.drop_index('ix_holding_filing_security', table_name='holding')
    op.drop_index(op.f('ix_holding_filing_id'), table_name='holding')
    op.drop_table('holding')
    op.drop_index(op.f('ix_fund_holding_security_id'), table_name='fund_holding')
    op.drop_index(op.f('ix_fund_holding_filing_id'), table_name='fund_holding')
    op.drop_table('fund_holding')
    op.drop_index(op.f('ix_holding_change_security_id'), table_name='holding_change')
    op.drop_index(op.f('ix_holding_change_period'), table_name='holding_change')
    op.drop_index(op.f('ix_holding_change_filer_id'), table_name='holding_change')
    op.drop_index(op.f('ix_holding_change_action'), table_name='holding_change')
    op.drop_index('ix_change_filer_period', table_name='holding_change')
    op.drop_table('holding_change')
    op.drop_index(op.f('ix_filing_period_of_report'), table_name='filing')
    op.drop_index(op.f('ix_filing_form_type'), table_name='filing')
    op.drop_index(op.f('ix_filing_filer_id'), table_name='filing')
    op.drop_index(op.f('ix_filing_filed_at'), table_name='filing')
    op.drop_index(op.f('ix_filing_accession_no'), table_name='filing')
    op.drop_table('filing')
    op.drop_index(op.f('ix_security_ticker'), table_name='security')
    op.drop_index(op.f('ix_security_name'), table_name='security')
    op.drop_index(op.f('ix_security_key'), table_name='security')
    op.drop_index(op.f('ix_security_cusip'), table_name='security')
    op.drop_table('security')
    op.drop_index(op.f('ix_filer_name'), table_name='filer')
    op.drop_index(op.f('ix_filer_cik'), table_name='filer')
    op.drop_table('filer')
    # ### end Alembic commands ###
